# Generated by Django 4.2.19 on 2025-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('room_type_desc', models.CharField(max_length=200)),
                ('number_of_beds', models.IntegerField()),
                ('roomtype_photo_main', models.CharField(max_length=100)),
                ('roomtype_photo_1', models.CharField(max_length=100)),
                ('roomtype_photo_2', models.CharField(max_length=100)),
                ('roomtype_photo_3', models.CharField(max_length=100)),
                ('roomtype_photo_4', models.CharField(max_length=100)),
                ('roomtype_photo_5', models.CharField(max_length=100)),
                ('max_no_of_room_for_roomtype', models.IntegerField()),
                ('standard_price', models.IntegerField()),
                ('week_date_price', models.IntegerField()),
                ('week_end_price', models.IntegerField()),
                ('peak_season_price', models.IntegerField()),
                ('special_price', models.IntegerField()),
                ('with_breakfast_standard_price', models.IntegerField()),
                ('with_breakfast_week_date_price', models.IntegerField()),
                ('with_breakfast_week_end_price', models.IntegerField()),
                ('with_breakfast_peak_season_price', models.IntegerField()),
                ('with_breakfast_special_price', models.IntegerField()),
            ],
        ),
    ]
