# Generated by Django 4.2.19 on 2025-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomtypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='roomtype_photo_1',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomtype_photo_2',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomtype_photo_3',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomtype_photo_4',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomtype_photo_5',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomtype_photo_main',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
